version: '2'

services:
    nginx:
        image: nginx:alpine
        ports:
          - "80:80"
        volumes:
          - ./src:/var/www
          - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        links:
          - fpm
    fpm:
        image: bitnami/php-fpm:latest
        volumes:
          - ./src:/var/www
          - tmp:/var/www/tmp
        links:
          - database
    database:
        image: mariadb
        ports:
          - "3306:3306"
        expose:
          - 3306
        volumes:
          - db_data:/var/lib/mysql
        environment:
          - MYSQL_USER=user
          - MYSQL_PASSWORD=password
          - MYSQL_DATABASE=test
          - MYSQL_ROOT_PASSWORD=password
volumes:
    db_data:
    tmp: