nginx:
    image: nginx:alpine
    ports:
        - "8080:80"
    volumes:
        - ./src:/var/www
        - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - fpm
fpm:
    image: bitnami/php-fpm
    volumes:
        - ./src:/var/www
    links:
        - database
database:
    image: mariadb
    environment:
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
        - MYSQL_DATABASE=test
        - MYSQL_ROOT_PASSWORD=password